build:
  install:
    image: node:5
    commands:
      - npm i -g yarn
      - yarn
  lint:
    image: node:5
    commands:
      - npm run lint
  test:
    image: node:5
    commands:
      - npm test

cache:
  mount:
    - /drone/.npm